apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mumble-server.fullname" . }}
  labels:
    {{- include "mumble-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mumble-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mumble-server.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: mumble-tcp
              containerPort: {{ .Values.config.port }}
              protocol: TCP
            - name: mumble-udp
              containerPort: {{ .Values.config.port }}
              protocol: UDP
          env:
            # Server config
            - name: MUMBLE_CONFIG_DATABASE
              value: "{{ .Values.config.database }}"
            - name: MUMBLE_CONFIG_DB_DRIVER
              value: "{{ .Values.config.dbDriver }}"
            - name: MUMBLE_CONFIG_DB_USERNAME
              value: "{{ .Values.config.dbUsername }}"
            - name: MUMBLE_CONFIG_DB_PASSWORD
              value: "{{ .Values.config.dbPassword }}"
            - name: MUMBLE_CONFIG_DB_HOST
              value: "{{ .Values.config.dbHost }}"
            - name: MUMBLE_CONFIG_DB_PORT
              value: "{{ .Values.config.dbPort }}"
            - name: MUMBLE_CONFIG_WELCOME_TEXT
              value: "{{ .Values.config.welcometext }}"
            - name: MUMBLE_CONFIG_PORT
              value: "{{ .Values.config.port }}"
            - name: MUMBLE_CONFIG_SERVER_PASSWORD
              value: "{{ .Values.config.serverpassword }}"
            - name: MUMBLE_CONFIG_BANDWIDTH
              value: "{{ .Values.config.bandwidth }}"
            - name: MUMBLE_CONFIG_USERS
              value: "{{ .Values.config.users }}"
            - name: MUMBLE_CONFIG_MESSAGE_BURST
              value: "{{ .Values.config.messageburst }}"
            - name: MUMBLE_CONFIG_MESSAGE_LIMIT
              value: "{{ .Values.config.messagelimit }}"
            - name: MUMBLE_CONFIG_ALLOW_PING
              value: "{{ .Values.config.allowping }}"
            # Docker image config
            - name: MUMBLE_SUPERUSER_PASSWORD
              value: "{{ .Values.config.superuserpassword }}"
            - name: MUMBLE_VERBOSE
              value: "true"
          livenessProbe:
            tcpSocket:
              port: mumble-tcp
          readinessProbe:
            tcpSocket:
              port: mumble-tcp
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
