{{ if not .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mumble-server.fullname" . }}
  labels:
    {{- include "mumble-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  databasePassword: "{{ .Values.config.databasePassword}}"
  serverPassword: "{{ .Values.config.serverPassword }}"
  superUserPassword: "{{ .Values.config.superUserPassword}}"
{{- end }}